#index:
    #path: /
    #controller: AppBundle:Student:index # src\Controller\StudentController::index
    #defaults:
       #_controller: AppBundle:Student:index
       #template:  'student/index.html.twig'

#app_student_index:
    #path: /student/
    #controller: App\Controller\StudentController::index
    #defaults: { _controller: AppBundle:Student:index }

rest_controller:
    type: annotation
    prefix: '/api'

