index:
    path: /
    controller: App\Controller\StudentController::index

app_student_index:
    path: /student/
    controller: App\Controller\StudentController::index

rest_controller:
    resource: ../../src/Controller/Rest/
    type: annotation
    prefix: /api

